### ISSUE TITLE
Got an error if starting TheDoor.py

### ISSUE THREAD

**Issue by yelloff** [plenkyman/RFID_RC522_Python3_TheDoor#3]
Unhandled exception in thread started by <function checkme at 0x76606150>
Traceback (most recent call last):
  File "./TheDoor.py", line 52, in checkme
    with open(tdp.p2pipe,"r") as tdpipe:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/thedoor/system/fifo/thedoor.pipe'

**Comment by thowitz** [comment]
I got an error too and in setupcards.py

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pymysql/connections.py", line 571, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SetupCards.py", line 26, in <module>
    connection = pymysql.connect(host=tdp.rpi_ip,unix_socket='/var/run/mysqld/mysqld.sock', user=tdp.dbUs, passwd=tdp.dbPW, db=tdp.dbNa)
  File "/usr/local/lib/python3.7/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 2] No such file or directory)")
